In [2]:
import numpy as np

In [3]:
# №1
arr = np.arange(1, 111)
np.reshape(arr, (11, 10))[:, :-3]

array([[  1,   2,   3,   4,   5,   6,   7],
       [ 11,  12,  13,  14,  15,  16,  17],
       [ 21,  22,  23,  24,  25,  26,  27],
       [ 31,  32,  33,  34,  35,  36,  37],
       [ 41,  42,  43,  44,  45,  46,  47],
       [ 51,  52,  53,  54,  55,  56,  57],
       [ 61,  62,  63,  64,  65,  66,  67],
       [ 71,  72,  73,  74,  75,  76,  77],
       [ 81,  82,  83,  84,  85,  86,  87],
       [ 91,  92,  93,  94,  95,  96,  97],
       [101, 102, 103, 104, 105, 106, 107]])

In [6]:
# №2
row = np.arange(2, 20)
ev = row[row % 2 == 0]
odd = row[row % 2 != 0]
ev, odd, ev*odd

(array([ 2,  4,  6,  8, 10, 12, 14, 16, 18]),
 array([ 3,  5,  7,  9, 11, 13, 15, 17, 19]),
 array([  6,  20,  42,  72, 110, 156, 210, 272, 342]))

In [7]:
# №3
a = np.random.randint(0, 11, (30,3))
b = np.random.randint(0, 11, (30,3))
a, b

(array([[ 0,  9,  5],
        [ 0, 10,  9],
        [ 2,  7,  7],
        [ 8,  6,  2],
        [ 8,  9,  2],
        [ 8,  6,  9],
        [ 8,  2,  6],
        [ 4, 10, 10],
        [ 2,  8,  7],
        [ 3,  4,  7],
        [ 1,  5,  3],
        [ 0,  6,  1],
        [ 7,  4,  7],
        [ 9,  5, 10],
        [ 4,  1,  2],
        [ 7,  8,  8],
        [ 9,  4,  8],
        [ 3,  9,  8],
        [10,  2,  6],
        [ 5,  7,  6],
        [ 5,  1,  3],
        [ 8, 10,  9],
        [ 2,  3,  3],
        [10,  7,  1],
        [ 7,  9,  1],
        [ 9,  2,  0],
        [ 6,  8,  0],
        [10,  7,  8],
        [ 8,  7,  7],
        [ 5,  1,  1]]),
 array([[ 1,  7,  5],
        [ 1,  2,  5],
        [ 5,  4,  2],
        [ 5,  5,  2],
        [ 7,  0,  6],
        [ 4,  9,  7],
        [ 1,  4,  7],
        [ 0,  4,  3],
        [ 1,  3, 10],
        [ 6,  3,  0],
        [ 7,  3,  8],
        [ 6,  3,  4],
        [10,  0,  8],
        [ 9,  5,  2],
        [ 9, 10,  5],
        [ 2,  8,  5],
        [ 0,  0,  1],
        [ 4, 10,  6],
        [ 8, 10,  2],
        [ 5,  3,  1],
        [ 4,  3, 10],
        [ 9,  7,  9],
        [ 1, 10,  0],
        [ 8,  9,  9],
        [ 7,  2,  1],
        [ 3,  8,  2],
        [ 3,  3,  5],
        [ 4,  9,  0],
        [ 8,  2,  7],
        [ 4,  7,  7]]))

In [13]:
d = a[a-b>0]
d, d.sum()

(array([ 9, 10,  9,  7,  7,  8,  6,  8,  9,  8,  9,  8,  4, 10, 10,  2,  8,
         4,  7,  5,  6,  4, 10,  7,  8,  9,  4,  8,  8, 10,  6,  7,  6,  5,
        10,  2,  3, 10,  9,  9,  6,  8, 10,  8,  7,  5]),
 333)

In [15]:
# или так:
g = np.where(a-b > 0, a, 0)
g, g.sum()

(array([[ 0,  9,  0],
        [ 0, 10,  9],
        [ 0,  7,  7],
        [ 8,  6,  0],
        [ 8,  9,  0],
        [ 8,  0,  9],
        [ 8,  0,  0],
        [ 4, 10, 10],
        [ 2,  8,  0],
        [ 0,  4,  7],
        [ 0,  5,  0],
        [ 0,  6,  0],
        [ 0,  4,  0],
        [ 0,  0, 10],
        [ 0,  0,  0],
        [ 7,  0,  8],
        [ 9,  4,  8],
        [ 0,  0,  8],
        [10,  0,  6],
        [ 0,  7,  6],
        [ 5,  0,  0],
        [ 0, 10,  0],
        [ 2,  0,  3],
        [10,  0,  0],
        [ 0,  9,  0],
        [ 9,  0,  0],
        [ 6,  8,  0],
        [10,  0,  8],
        [ 0,  7,  0],
        [ 5,  0,  0]]),
 333)

In [147]:
# №4
def tl(n, m):
    return np.tile([[0, 1], [2, 3]], (m//2+1, n//2+1))[:m, :n]
    
tl(5, 4)

array([[0, 1, 0, 1, 0],
       [2, 3, 2, 3, 2],
       [0, 1, 0, 1, 0],
       [2, 3, 2, 3, 2]])

In [5]:
# №5
x = np.random.randint(10, size=(20, 20))

a = np.arange(19)
x, x[a, a+1]

(array([[1, 1, 4, 3, 3, 1, 5, 8, 2, 2, 4, 1, 8, 5, 8, 9, 0, 5, 6, 0],
        [3, 3, 1, 7, 1, 2, 6, 3, 7, 7, 0, 2, 6, 7, 6, 9, 9, 9, 9, 7],
        [1, 2, 1, 2, 6, 5, 6, 6, 9, 4, 4, 7, 6, 5, 0, 2, 5, 4, 6, 9],
        [4, 9, 3, 4, 2, 4, 6, 7, 1, 2, 8, 7, 0, 0, 2, 0, 5, 9, 8, 8],
        [3, 6, 9, 1, 5, 7, 4, 7, 9, 3, 8, 1, 3, 6, 9, 2, 0, 7, 0, 3],
        [0, 9, 4, 0, 2, 9, 5, 4, 7, 7, 4, 5, 6, 6, 8, 4, 3, 7, 9, 7],
        [3, 6, 6, 0, 3, 9, 9, 5, 5, 2, 9, 0, 2, 4, 0, 6, 7, 1, 6, 5],
        [0, 0, 5, 7, 7, 4, 1, 6, 6, 8, 5, 9, 2, 4, 4, 9, 0, 2, 3, 0],
        [6, 9, 2, 9, 2, 2, 7, 7, 3, 2, 0, 6, 1, 3, 3, 6, 4, 7, 5, 3],
        [4, 3, 5, 2, 5, 6, 8, 4, 4, 8, 5, 8, 8, 5, 9, 6, 0, 0, 1, 2],
        [9, 1, 5, 6, 1, 1, 1, 7, 3, 4, 7, 4, 6, 4, 0, 7, 0, 0, 2, 7],
        [2, 5, 0, 4, 7, 5, 2, 9, 2, 8, 6, 4, 2, 0, 1, 4, 1, 3, 7, 1],
        [0, 5, 7, 5, 1, 3, 0, 7, 1, 3, 9, 9, 7, 9, 7, 3, 6, 8, 3, 1],
        [8, 2, 8, 0, 0, 1, 4, 2, 4, 1, 8, 6, 7, 5, 3, 6, 3, 3, 6, 2],
        [1, 0, 7, 9, 0, 0, 9, 1, 6, 8, 2, 0, 4, 6, 3, 9, 8, 3, 3, 2],
        [0, 8, 1, 4, 4, 9, 7, 7, 0, 6, 1, 0, 6, 6, 8, 0, 9, 9, 2, 9],
        [2, 4, 3, 4, 1, 1, 0, 6, 2, 9, 7, 7, 1, 4, 0, 5, 4, 0, 0, 9],
        [0, 1, 5, 3, 4, 7, 2, 1, 4, 2, 7, 1, 5, 2, 4, 1, 1, 3, 5, 4],
        [2, 6, 6, 9, 6, 0, 2, 3, 7, 8, 6, 0, 2, 5, 3, 2, 4, 2, 3, 6],
        [9, 2, 6, 4, 5, 5, 7, 2, 1, 1, 0, 7, 0, 3, 2, 3, 3, 5, 4, 4]]),
 array([1, 1, 2, 2, 7, 5, 5, 6, 2, 5, 4, 2, 9, 3, 9, 9, 0, 5, 6]))

In [6]:
# №6
X = ['Москва','Питер','Саратов','Могилев','Одесса','Ялта','Мадрид','Милан','Вашингтон','Астана']
r = np.random.choice(X, 100, replace=True)
r

array(['Мадрид', 'Питер', 'Вашингтон', 'Саратов', 'Мадрид', 'Одесса',
       'Милан', 'Вашингтон', 'Мадрид', 'Саратов', 'Астана', 'Одесса',
       'Милан', 'Вашингтон', 'Саратов', 'Москва', 'Мадрид', 'Мадрид',
       'Ялта', 'Саратов', 'Ялта', 'Вашингтон', 'Астана', 'Милан',
       'Саратов', 'Мадрид', 'Вашингтон', 'Мадрид', 'Одесса', 'Милан',
       'Могилев', 'Саратов', 'Москва', 'Ялта', 'Одесса', 'Саратов',
       'Могилев', 'Милан', 'Астана', 'Одесса', 'Саратов', 'Одесса',
       'Ялта', 'Могилев', 'Могилев', 'Питер', 'Астана', 'Одесса', 'Ялта',
       'Могилев', 'Могилев', 'Одесса', 'Милан', 'Ялта', 'Одесса',
       'Могилев', 'Саратов', 'Одесса', 'Москва', 'Ялта', 'Вашингтон',
       'Москва', 'Питер', 'Вашингтон', 'Ялта', 'Астана', 'Милан', 'Милан',
       'Саратов', 'Одесса', 'Мадрид', 'Ялта', 'Вашингтон', 'Ялта', 'Ялта',
       'Москва', 'Саратов', 'Могилев', 'Вашингтон', 'Питер', 'Москва',
       'Саратов', 'Москва', 'Могилев', 'Вашингтон', 'Ялта', 'Могилев',
       'Ялта', 'Астана', 'Москва', 'Могилев', 'Вашингтон', 'Одесса',
       'Астана', 'Москва', 'Вашингтон', 'Саратов', 'Питер', 'Одесса',
       'Мадрид'], dtype='<U9')

In [7]:
# №7
desc = np.zeros((8,8))

desc[6,:].fill(1)
desc[7, 0::7] = 4
desc[7, 1::5] = 3
desc[7, 2::3] = 2
desc[7, 3:5] = (6, 5)

desc[::-1, ::-1]*-1 + desc

array([[-4., -3., -2., -5., -6., -2., -3., -4.],
       [-1., -1., -1., -1., -1., -1., -1., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 4.,  3.,  2.,  6.,  5.,  2.,  3.,  4.]])

In [9]:
# №8
src = np.random.randint(100, size=(20, 3))
ln = list(map(lambda x: np.linalg.norm(x), src))

x = src[np.argsort(ln)]
src, x

(array([[71, 34, 94],
        [53, 46, 34],
        [32, 41, 17],
        [71, 83, 47],
        [31, 86, 27],
        [ 4, 99,  1],
        [29, 24, 61],
        [34, 29, 23],
        [27, 39,  4],
        [54, 58, 99],
        [91,  2, 87],
        [ 0, 94, 52],
        [22, 12, 98],
        [ 0, 19, 29],
        [27, 86, 72],
        [51, 90, 44],
        [49, 28,  3],
        [31, 29, 32],
        [65, 39, 81],
        [30, 86, 10]]),
 array([[ 0, 19, 29],
        [27, 39,  4],
        [34, 29, 23],
        [31, 29, 32],
        [32, 41, 17],
        [49, 28,  3],
        [29, 24, 61],
        [53, 46, 34],
        [30, 86, 10],
        [31, 86, 27],
        [ 4, 99,  1],
        [22, 12, 98],
        [ 0, 94, 52],
        [65, 39, 81],
        [51, 90, 44],
        [27, 86, 72],
        [71, 83, 47],
        [71, 34, 94],
        [91,  2, 87],
        [54, 58, 99]]))

In [10]:
# №9
x = np.arange(0, 110, 10)[:, np.newaxis]
y = np.arange(1, 8)

x+y

array([[  1,   2,   3,   4,   5,   6,   7],
       [ 11,  12,  13,  14,  15,  16,  17],
       [ 21,  22,  23,  24,  25,  26,  27],
       [ 31,  32,  33,  34,  35,  36,  37],
       [ 41,  42,  43,  44,  45,  46,  47],
       [ 51,  52,  53,  54,  55,  56,  57],
       [ 61,  62,  63,  64,  65,  66,  67],
       [ 71,  72,  73,  74,  75,  76,  77],
       [ 81,  82,  83,  84,  85,  86,  87],
       [ 91,  92,  93,  94,  95,  96,  97],
       [101, 102, 103, 104, 105, 106, 107]])

In [31]:
# №10
r = np.random.randint(0, 100, 20)
u = np.unique(r)
r, u[-2], np.argwhere(r == u[-2])

(array([69,  8, 76, 46, 73, 66, 67, 80,  2, 84, 76, 47,  0, 97, 75, 52, 70,
        93, 82, 11]),
 93,
 array([[17]], dtype=int64))

In [32]:
# №11
arr = np.random.random(100)
val = 0.75

idx = (np.abs(arr - val)).argmin()
arr[idx]

0.7423759095056699

In [33]:
# №12
ar1, ar2 = np.random.randint(0, 11, (4, 7)), np.random.randint(0, 11, (4, 7))
ar1, ar2, np.maximum(ar1, ar2)

(array([[10,  4,  0,  4, 10,  3, 10],
        [ 2,  9,  2,  2,  0,  2,  5],
        [ 0,  0,  5,  4, 10,  9,  4],
        [ 1,  1,  2,  6,  9,  1,  9]]),
 array([[ 7,  5,  2,  9,  0, 10,  0],
        [ 0,  0,  3,  2,  8,  9, 10],
        [ 6,  5,  8,  9,  0,  7,  0],
        [ 1, 10, 10,  1,  5,  4,  1]]),
 array([[10,  5,  2,  9, 10, 10, 10],
        [ 2,  9,  3,  2,  8,  9, 10],
        [ 6,  5,  8,  9, 10,  9,  4],
        [ 1, 10, 10,  6,  9,  4,  9]]))